# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- master

# Variables
variables:
  tag: '$(Build.BuildId)'
  dockerfileSsoServer: "$(Build.SourcesDirectory)/sso-server/Dockerfile"

stages:
# Build Stage 
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps: 

    - task: Docker@2
      inputs:
        containerRegistry: 'ssov2'
        repository: 'sso-server'
        command: 'buildAndPush'
        Dockerfile: $(dockerfileSsoServer)